image: node:latest

#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest
#  - docker:19.03.12-dind
#
#before_script:
#  - docker info
#
#build:
#  stage: build
#  script:
#    - docker build -t my-docker-image .
#    - docker run my-docker-image /script/to/run/tests
#
#cache:
#  paths:
#    - node_modules/
#
#test_async:
#  script:
#    - npm install
#    - node ./specs/start.js ./specs/async.spec.js
#
#test_db:
#  script:
#    - npm install
#    - node ./specs/start.js ./specs/db-postgres.spec.js
