image: docker:latest
services:
  - docker:dind
stages:
  - build
  - deploy
build_image:
  stage: build
  variables:
    IMAGE_TAG:
  script:
    - docker login -u gitlab-ci-token -p "CI_JOB_TOKEN $CI_REGISTRY"
    - docker build --pull -t $IMAGE_TAG -f dockerfile .
    - docker push $IMAGE_TAG
